/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsTokenUsage {
  input: number
  output: number
}
export interface JsForgeParticipant {
  id: string
  name: string
  type: string
  role: string
  modelId?: string
  status: string
}
export interface JsForgeOracle {
  id: string
  name: string
  modelId: string
  config: string
}
export interface JsForgeSessionConfig {
  maxRounds: number
  convergenceThreshold: number
  roundTimeoutMs: number
  allowHumanIntervention: boolean
}
export interface JsForgeSessionRequest {
  name: string
  goal: string
  participants: Array<JsForgeParticipant>
  oracle?: JsForgeOracle
  config: JsForgeSessionConfig
}
export interface JsForgeSessionResponse {
  id: string
  name: string
  goal: string
  phase: string
  participants: Array<JsForgeParticipant>
  oracle?: JsForgeOracle
  config: JsForgeSessionConfig
  roundCount: number
  totalCostUsd: number
  totalTokens: JsTokenUsage
  createdAt: string
  updatedAt: string
}
export declare function createForgeSession(request: JsForgeSessionRequest): JsForgeSessionResponse
export declare function getSession(sessionId: string): JsForgeSessionResponse | null
export declare function listSessions(): Array<JsForgeSessionResponse>
export declare function startDeliberation(sessionId: string): DeliberationStream
export declare function stopDeliberation(sessionId: string): boolean
export declare class DeliberationStream {
  next(): Promise<string | null>
  close(): void
}
